(() => {
  const KEY = 'lineup-hockey-v1';
  const POS = { goalie: 'Gardien', defense: 'Défenseur', attack: 'Attaquant' };
  const $ = (s, p=document) => p.querySelector(s);
  const id = () => crypto.randomUUID?.() || `${Date.now()}-${Math.random()}`;
  const defaults = { players: [], history: [], settings: { white: 'Blancs', black: 'Noirs', balancePositions: true, historyDepth: 3 }, match: { present: [], goalies: [], teams: null } };
  let state;
  try { state = { ...defaults, ...JSON.parse(localStorage.getItem(KEY)) }; state.settings = {...defaults.settings, ...state.settings}; state.match = {...defaults.match, ...state.match}; } catch { state = structuredClone(defaults); }
  let view = 'match', editing = null;
  const save = () => localStorage.setItem(KEY, JSON.stringify(state));
  const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const present = () => state.players.filter(p => state.match.present.includes(p.id));
  const playerPos = p => Object.keys(POS).filter(k => p.positions?.includes(k));
  const rating = (p, pos) => Number(p.ratings?.[pos] || 0);
  const candidateGoalies = () => present().filter(p => p.positions.includes('goalie'));
  function rosterText(t) { return t.map(x => `${x.position === 'goalie' ? 'G' : x.position === 'defense' ? 'D' : 'A'} — ${x.player.name}`).join(', '); }
  function historyPenalty(a,b,teamA,teamB) { const recent=state.history.slice(0,state.settings.historyDepth); let n=0; for(const m of recent){const at=m.teams?.white?.some(x=>x.player.id===a.id), bt=m.teams?.white?.some(x=>x.player.id===b.id); const same=(at&&bt)||(!at&&!bt); n+=same===teamA?1:.65;} return n; }
  function assignPositions(players) {
    const slots=[]; const desired = state.settings.balancePositions;
    if(desired){['defense','defense','attack','attack'].forEach(x=>slots.push(x));}
    return players.map((p,i) => { let available=playerPos(p).filter(x=>x!=='goalie'); let pos=slots.find(x=>available.includes(x)); if(pos) slots.splice(slots.indexOf(pos),1); else pos=available.sort((a,b)=>rating(p,b)-rating(p,a))[0] || 'attack'; return {player:p,position:pos}; });
  }
  function evaluate(white,black){
    const stats=t=>{const grouped={goalie:0,defense:0,attack:0}; const counts={goalie:0,defense:0,attack:0}; t.forEach(x=>{grouped[x.position]+=rating(x.player,x.position);counts[x.position]++}); const skaters=t.filter(x=>x.position!=='goalie');const subs=Math.max(0,skaters.length-4);const cardio=skaters.length?skaters.reduce((a,x)=>a+Number(x.player.cardio),0)/skaters.length:0;return {grouped,counts,cardio,subs,total:Object.values(grouped).reduce((a,b)=>a+b,0)+cardio*(1-Math.min(subs,4)/4)};}; const a=stats(white),b=stats(black); let score=Math.abs(a.total-b.total)+Math.abs(a.grouped.defense-b.grouped.defense)+Math.abs(a.grouped.attack-b.grouped.attack); if(state.settings.balancePositions) score+=Math.abs(a.counts.defense-b.counts.defense)*5+Math.abs(a.counts.attack-b.counts.attack)*5; for(const x of white)for(const y of black)score+=historyPenalty(x.player,y.player,false,true)*.8; for(const list of [white,black])for(let i=0;i<list.length;i++)for(let j=i+1;j<list.length;j++)score+=historyPenalty(list[i].player,list[j].player,true,false)*.8; return {score,a,b}; }
  function generate(){ const gs=state.match.goalies.map(i=>state.players.find(p=>p.id===i)).filter(Boolean); if(gs.length!==2){return alert('Désignez exactement deux gardiens avant de générer les équipes.');} const others=present().filter(p=>!gs.includes(p)); if(others.length<8) return alert('Il faut au moins 8 joueurs en plus des deux gardiens pour viser 2 défenseurs et 2 attaquants par équipe.'); let best; for(let n=0;n<3500;n++){const shuffled=[...others].sort(()=>Math.random()-.5);const half=Math.ceil(shuffled.length/2);const white=[{player:gs[0],position:'goalie'},...assignPositions(shuffled.slice(0,half))];const black=[{player:gs[1],position:'goalie'},...assignPositions(shuffled.slice(half))];const e=evaluate(white,black);if(!best||e.score<best.score)best={white,black};} state.match.teams=best;save();render(); }
  function stats(team){if(!team)return null;const s=evaluate(team,[]).a;return s;}
  function matchView(){const ps=present(), cs=candidateGoalies(), teams=state.match.teams; return `<section class="grid split"><div class="card"><h2>Présences</h2><p class="muted">${ps.length} joueur${ps.length!==1?'s':''} sélectionné${ps.length!==1?'s':''}. Choisissez ensuite les deux gardiens.</p>${state.players.length?`<div class="presence-list">${state.players.map(p=>`<label class="presence"><input data-present="${p.id}" type="checkbox" ${ps.includes(p)?'checked':''}><span><strong>${esc(p.name)}</strong><small>${playerPos(p).map(x=>POS[x]).join(' · ')} · Cardio ${p.cardio}</small></span></label>`).join('')}</div>`:'<p class="empty">Ajoutez des joueurs dans l’onglet Joueurs.</p>'}<div class="goalie-choice"><strong>Gardiens :</strong>${cs.map(p=>`<label><input data-goalie="${p.id}" type="checkbox" ${state.match.goalies.includes(p.id)?'checked':''}> ${esc(p.name)}</label>`).join('')||'<span class="muted">Aucun gardien disponible</span>'}</div><div class="settings"><label class="switch"><input data-balance type="checkbox" ${state.settings.balancePositions?'checked':''}> Équilibrer les positions</label><label class="range">Variété (0–5) <input data-depth type="range" min="0" max="5" value="${state.settings.historyDepth}"><output>${state.settings.historyDepth}</output></label></div><div class="controls" style="margin-top:16px"><button data-action="generate" class="button primary">Mélanger les équipes</button>${teams?'<button data-action="archive" class="button">Archiver ce match</button>':''}</div></div><div class="card"><h2>À retenir</h2><p class="muted">La génération équilibre les niveaux de défense et d’attaque, le cardio et les répétitions récentes. Le cardio compte davantage quand il y a moins de remplaçants.</p><div class="notice ${state.match.goalies.length===2?'':'error'}">${state.match.goalies.length===2?'Deux gardiens sont désignés.':'Désignez exactement deux gardiens pour lancer la génération.'}</div><div class="position-legend"><span><i class="dot goal"></i>Gardien</span><span><i class="dot def"></i>Défenseur</span><span><i class="dot att"></i>Attaquant</span></div></div></section>${teams?teamsView(teams):''}`; }
  function teamCard(key,team){const name=state.settings[key];const color=key==='white'?'#f0b429':'#17233a';return `<article class="card" style="--team:${color}"><header class="team-header"><h2>${esc(name)}</h2><span>${team.length} joueurs</span></header><ul class="team-roster">${team.map((x,i)=>`<li class="player-row"><span><strong>${esc(x.player.name)}</strong> <span class="badge">${POS[x.position]}</span><br><small class="muted">Niveau ${rating(x.player,x.position)} · Cardio ${x.player.cardio}</small></span><select class="team-select" data-role="${key}:${i}">${playerPos(x.player).filter(p=>p!=='goalie'||x.position==='goalie').map(p=>`<option value="${p}" ${p===x.position?'selected':''}>${POS[p]}</option>`).join('')}</select><select class="team-select" data-team="${key}:${i}"><option value="white" ${key==='white'?'selected':''}>${esc(state.settings.white)}</option><option value="black" ${key==='black'?'selected':''}>${esc(state.settings.black)}</option></select></li>`).join('')}</ul></article>`;}
  function teamsView(t){const e=evaluate(t.white,t.black);return `<section class="grid split" style="margin-top:20px">${teamCard('white',t.white)}${teamCard('black',t.black)}</section><section class="card" style="margin-top:20px"><h2>Équilibre des équipes</h2>${statsTable(e)}<div class="charts">${barChart(e)}${positionChart(e)}</div></section><section class="card" style="margin-top:20px"><h2>Message aux joueurs</h2><textarea id="share-text" class="share" readonly>${esc(shareText(t))}</textarea><div class="controls" style="margin-top:10px"><button data-action="copy" class="button primary">Copier</button><a data-share-email class="button" href="#">E-mail</a><a data-share-sms class="button" href="#">SMS</a></div></section>`;}
  function statsTable(e){const rows=[['Joueurs',e.a.counts.goalie+e.a.counts.defense+e.a.counts.attack,e.b.counts.goalie+e.b.counts.defense+e.b.counts.attack],['Gardiens',e.a.counts.goalie,e.b.counts.goalie],['Défenseurs',e.a.counts.defense,e.b.counts.defense],['Attaquants',e.a.counts.attack,e.b.counts.attack],['Remplaçants',e.a.subs,e.b.subs],['Force défense',e.a.grouped.defense.toFixed(1),e.b.grouped.defense.toFixed(1)],['Force attaque',e.a.grouped.attack.toFixed(1),e.b.grouped.attack.toFixed(1)],['Cardio moyen',e.a.cardio.toFixed(1),e.b.cardio.toFixed(1)],['Force ajustée',e.a.total.toFixed(1),e.b.total.toFixed(1)]];return `<table class="stat-table"><thead><tr><th>Statistique</th><th>${esc(state.settings.white)}</th><th>${esc(state.settings.black)}</th><th>Écart</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td class="delta">${Math.abs(r[1]-r[2]).toFixed(1)}</td></tr>`).join('')}</tbody></table>`;}
  function barChart(e){const data=[['Défense',e.a.grouped.defense,e.b.grouped.defense],['Attaque',e.a.grouped.attack,e.b.grouped.attack],['Cardio',e.a.cardio,e.b.cardio],['Force ajustée',e.a.total,e.b.total]],max=Math.max(...data.flatMap(x=>x.slice(1)),1),bars=data.map((d,i)=>{const y=35+i*42;return `<text x="0" y="${y+13}">${d[0]}</text><rect x="108" y="${y}" width="${d[1]/max*220}" height="14" fill="#f0b429"/><text x="${113+d[1]/max*220}" y="${y+12}">${d[1].toFixed(1)}</text><rect x="108" y="${y+18}" width="${d[2]/max*220}" height="14" fill="#17233a"/><text x="${113+d[2]/max*220}" y="${y+30}">${d[2].toFixed(1)}</text>`}).join('');return `<div><h3>Forces comparées</h3><svg class="chart" viewBox="0 0 390 215" role="img" aria-label="Comparaison des forces des équipes"><title>Forces comparées</title>${bars}</svg><p class="muted"><span class="dot" style="background:#f0b429"></span>${esc(state.settings.white)} <span class="dot" style="background:#17233a"></span>${esc(state.settings.black)}</p></div>`;}
  function positionChart(e){const data=[['Gardien',e.a.counts.goalie,e.b.counts.goalie],['Défense',e.a.counts.defense,e.b.counts.defense],['Attaque',e.a.counts.attack,e.b.counts.attack]];return `<div><h3>Répartition des positions</h3><svg class="chart" viewBox="0 0 300 185" role="img" aria-label="Répartition des positions"><title>Répartition des positions</title>${data.map((d,i)=>`<text x="0" y="${35+i*46}">${d[0]}</text><text x="115" y="${35+i*46}">${d[1]} / ${d[2]}</text><rect x="115" y="${42+i*46}" width="${d[1]*30}" height="12" fill="#f0b429"/><rect x="115" y="${57+i*46}" width="${d[2]*30}" height="12" fill="#17233a"/>`).join('')}</svg><p class="muted">Blancs / Noirs</p></div>`;}
  function shareText(t){return `Match de hockey\n\n${state.settings.white}\n${rosterText(t.white)}\n\n${state.settings.black}\n${rosterText(t.black)}\n\nÀ bientôt sur la glace !`;}
  function playersView(){return `<section class="grid split"><div class="card"><h2>${editing?'Modifier le joueur':'Ajouter un joueur'}</h2><div id="form-host"></div></div><div class="card"><div class="controls" style="justify-content:space-between"><h2>Le bassin (${state.players.length})</h2><button class="button" data-action="sample">Ajouter un exemple</button></div>${state.players.length?state.players.map(p=>`<div class="roster-row"><span><strong>${esc(p.name)}</strong><br><span class="positions">${playerPos(p).map(x=>`${POS[x]} ${rating(p,x)}`).join(' · ')} · Cardio ${p.cardio}</span></span><button class="button" data-edit="${p.id}">Modifier</button><button class="button danger" data-delete="${p.id}">Supprimer</button></div>`).join(''):'<p class="empty">Votre bassin est vide.</p>'}</div></section>`;}
  function historyView(){return `<section class="grid split"><div class="card"><h2>Réglages des équipes</h2><label>Nom de l’équipe blanche<input id="white-name" value="${esc(state.settings.white)}"></label><label>Nom de l’équipe noire<input id="black-name" value="${esc(state.settings.black)}"></label><p><button class="button primary" data-action="save-names">Enregistrer les noms</button></p><p class="muted">Les données restent uniquement dans ce navigateur.</p></div><div class="card"><h2>Historique</h2>${state.history.length?state.history.map((m,i)=>`<div class="history-item"><strong>${new Date(m.date).toLocaleDateString('fr-CA')}</strong><p>${esc(m.whiteName)} : ${esc(rosterText(m.teams.white))}</p><p>${esc(m.blackName)} : ${esc(rosterText(m.teams.black))}</p><button class="button danger" data-remove-history="${i}">Supprimer</button></div>`).join(''):'<p class="empty">Aucun match archivé.</p>'}</div></section>`;}
  function render(){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#app').innerHTML=view==='match'?matchView():view==='players'?playersView():historyView();if(view==='players')mountForm();if(state.match.teams){const text=shareText(state.match.teams);document.querySelectorAll('[data-share-email]').forEach(a=>a.href=`mailto:?subject=${encodeURIComponent('Équipes de hockey')}&body=${encodeURIComponent(text)}`);document.querySelectorAll('[data-share-sms]').forEach(a=>a.href=`sms:?body=${encodeURIComponent(text)}`)}}
  function mountForm(){const host=$('#form-host'), f=$('#player-form-template').content.cloneNode(true);host.append(f);const form=$('#player-form');if(editing){form.name.value=editing.name;form.goalie.checked=editing.positions.includes('goalie');form.defense.checked=editing.positions.includes('defense');form.attack.checked=editing.positions.includes('attack');form.goalieRating.value=rating(editing,'goalie');form.defenseRating.value=rating(editing,'defense');form.attackRating.value=rating(editing,'attack');form.cardio.value=editing.cardio;}form.addEventListener('submit',ev=>{ev.preventDefault();const d=new FormData(form),positions=['goalie','defense','attack'].filter(x=>d.has(x));if(!positions.length)return alert('Choisissez au moins une position.');const p={id:editing?.id||id(),name:d.get('name').trim(),positions,ratings:{goalie:+d.get('goalieRating'),defense:+d.get('defenseRating'),attack:+d.get('attackRating')},cardio:+d.get('cardio')};state.players=editing?state.players.map(x=>x.id===p.id?p:x):[...state.players,p];editing=null;save();render();});}
  document.addEventListener('click',e=>{const b=e.target.closest('button,[data-edit],[data-delete],[data-remove-history]');if(!b)return;if(b.dataset.view){view=b.dataset.view;render();return}if(b.dataset.action==='generate')generate();if(b.dataset.action==='archive'&&state.match.teams){state.history.unshift({date:new Date().toISOString(),teams:structuredClone(state.match.teams),whiteName:state.settings.white,blackName:state.settings.black});save();alert('Match archivé.');render();}if(b.dataset.action==='copy'){navigator.clipboard?.writeText($('#share-text').value);b.textContent='Copié !';}if(b.dataset.action==='cancel-player'){editing=null;render();}if(b.dataset.action==='save-names'){state.settings.white=$('#white-name').value.trim()||'Blancs';state.settings.black=$('#black-name').value.trim()||'Noirs';save();render();}if(b.dataset.action==='sample'){state.players.push({id:id(),name:'Alex Tremblay',positions:['defense','attack'],ratings:{goalie:0,defense:7,attack:6},cardio:8});save();render();}if(b.dataset.edit){editing=state.players.find(p=>p.id===b.dataset.edit);render();}if(b.dataset.delete&&confirm('Supprimer ce joueur ?')){state.players=state.players.filter(p=>p.id!==b.dataset.delete);state.match.present=state.match.present.filter(x=>x!==b.dataset.delete);state.match.goalies=state.match.goalies.filter(x=>x!==b.dataset.delete);save();render();}if(b.dataset.removeHistory!==undefined){state.history.splice(+b.dataset.removeHistory,1);save();render();}});
  document.addEventListener('change',e=>{if(e.target.dataset.present){const x=e.target.dataset.present;state.match.present=e.target.checked?[...new Set([...state.match.present,x])]:state.match.present.filter(i=>i!==x);state.match.goalies=state.match.goalies.filter(i=>state.match.present.includes(i));state.match.teams=null;}if(e.target.dataset.goalie){const x=e.target.dataset.goalie;state.match.goalies=e.target.checked?[...state.match.goalies,x]:state.match.goalies.filter(i=>i!==x);state.match.teams=null;}if(e.target.dataset.balance){state.settings.balancePositions=e.target.checked;state.match.teams=null;}if(e.target.dataset.depth){state.settings.historyDepth=+e.target.value;e.target.nextElementSibling.value=e.target.value;}if(e.target.dataset.role&&state.match.teams){const [team,i]=e.target.dataset.role.split(':');state.match.teams[team][+i].position=e.target.value;}if(e.target.dataset.team&&state.match.teams){const [from,i]=e.target.dataset.team.split(':'),to=e.target.value;if(from!==to){const [x]=state.match.teams[from].splice(+i,1);state.match.teams[to].push(x);}}save();render();});
  render();
})();
